version: '3'

services:

  # MySQL, backend, expose 3306
  app-database:
    image: mysql:5
    container_name: app-database
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      - backend
    expose:
      - "3306"
    volumes:
      - ./config/mysql:/etc/mysql:ro

  # Redis, backend, expose 6379
  app-redis:
    image: redis
    container_name: app-redis
    networks:
      - backend
    expose:
      - "6379"
    # volumes:
    #   - ./config/redis:/etc/redis:ro

  # KBS, frontend & backend, expose 8080 - 8082
  app-server:
    build: ./server
    container_name: app-server
    depends_on:
      - app-database
      - app-redis
    links:
      - app-database
      - app-redis
    networks:
      - frontend
      - backend
    expose:
      - "8080"
      - "8081"
      - "8082"
    volumes:
      - ./client:/app/client:ro

  # Nginx, frontend & backend & hostnet, ports 80 & 443 & 13306(dev) & 16379(dev)
  app-nginx:
    image: nginx
    container_name: app-nginx
    depends_on:
      - app-server
    links:
      - app-server
    networks:
      - frontend
      - backend
      - hostnet
    expose:
      - "80"
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "13306:3306"
    #   - "16379:6379"
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - ./client:/app:ro

networks:
  frontend:
  backend:
  hostnet:
    external: true
